# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\comparison_two_ships.ui',
# licensing of '.\comparison_two_ships.ui' applies.
#
# Created: Tue Dec 17 15:21:57 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ComparisonTwoShips(object):
    def setupUi(self, ComparisonTwoShips):
        ComparisonTwoShips.setObjectName("ComparisonTwoShips")
        ComparisonTwoShips.resize(630, 577)
        self.gridLayout = QtWidgets.QGridLayout(ComparisonTwoShips)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 3)
        self.levelComboBox = QtWidgets.QComboBox(ComparisonTwoShips)
        self.levelComboBox.setObjectName("levelComboBox")
        self.levelComboBox.addItem("")
        self.levelComboBox.addItem("")
        self.levelComboBox.addItem("")
        self.gridLayout.addWidget(self.levelComboBox, 0, 2, 1, 1)
        self.ship1GridLayout = QtWidgets.QGridLayout()
        self.ship1GridLayout.setObjectName("ship1GridLayout")
        self.line_11 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.ship1GridLayout.addWidget(self.line_11, 7, 0, 1, 6)
        self.ship1AmmunitionTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AmmunitionTitleLabel.setObjectName("ship1AmmunitionTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AmmunitionTitleLabel, 36, 0, 1, 1)
        self.ship2ImageLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2ImageLabel.setObjectName("ship2ImageLabel")
        self.ship1GridLayout.addWidget(self.ship2ImageLabel, 0, 4, 1, 1)
        self.ship1LuckTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1LuckTitleLabel.setObjectName("ship1LuckTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1LuckTitleLabel, 24, 0, 1, 1)
        self.ship2AntiairLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AntiairLabel.setObjectName("ship2AntiairLabel")
        self.ship1GridLayout.addWidget(self.ship2AntiairLabel, 20, 4, 1, 2)
        self.ship1TypeTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1TypeTitleLabel.setObjectName("ship1TypeTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1TypeTitleLabel, 2, 0, 1, 1)
        self.ship2NationLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2NationLabel.setObjectName("ship2NationLabel")
        self.ship1GridLayout.addWidget(self.ship2NationLabel, 4, 4, 1, 2)
        self.ship1AccuracyTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AccuracyTitleLabel.setObjectName("ship1AccuracyTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AccuracyTitleLabel, 28, 0, 1, 1)
        self.ship1SpeedLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1SpeedLabel.setObjectName("ship1SpeedLabel")
        self.ship1GridLayout.addWidget(self.ship1SpeedLabel, 26, 2, 1, 2)
        self.ship2HealthLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2HealthLabel.setObjectName("ship2HealthLabel")
        self.ship1GridLayout.addWidget(self.ship2HealthLabel, 10, 4, 1, 2)
        self.line_7 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.ship1GridLayout.addWidget(self.line_7, 15, 0, 1, 6)
        self.ship1AviationLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AviationLabel.setObjectName("ship1AviationLabel")
        self.ship1GridLayout.addWidget(self.ship1AviationLabel, 22, 2, 1, 2)
        self.line_16 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.ship1GridLayout.addWidget(self.line_16, 31, 0, 1, 6)
        self.ship1SpeedTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1SpeedTitleLabel.setObjectName("ship1SpeedTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1SpeedTitleLabel, 26, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.ship1GridLayout.addWidget(self.line_4, 9, 0, 1, 6)
        self.ship1AntisubTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AntisubTitleLabel.setObjectName("ship1AntisubTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AntisubTitleLabel, 30, 0, 1, 1)
        self.ship1TorpedoLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1TorpedoLabel.setObjectName("ship1TorpedoLabel")
        self.ship1GridLayout.addWidget(self.ship1TorpedoLabel, 14, 2, 1, 2)
        self.ship1AviationTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AviationTitleLabel.setObjectName("ship1AviationTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AviationTitleLabel, 22, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.ship1GridLayout.addWidget(self.line_8, 17, 0, 1, 6)
        self.ship1AntiairLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AntiairLabel.setObjectName("ship1AntiairLabel")
        self.ship1GridLayout.addWidget(self.ship1AntiairLabel, 20, 2, 1, 2)
        self.ship2ReloadLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2ReloadLabel.setObjectName("ship2ReloadLabel")
        self.ship1GridLayout.addWidget(self.ship2ReloadLabel, 18, 4, 1, 2)
        self.ship1OxygenTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1OxygenTitleLabel.setObjectName("ship1OxygenTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1OxygenTitleLabel, 34, 0, 1, 1)
        self.ship2EvasionLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2EvasionLabel.setObjectName("ship2EvasionLabel")
        self.ship1GridLayout.addWidget(self.ship2EvasionLabel, 16, 4, 1, 2)
        self.ship2AntisubLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AntisubLabel.setObjectName("ship2AntisubLabel")
        self.ship1GridLayout.addWidget(self.ship2AntisubLabel, 30, 4, 1, 2)
        self.ship1CostLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1CostLabel.setObjectName("ship1CostLabel")
        self.ship1GridLayout.addWidget(self.ship1CostLabel, 32, 2, 1, 2)
        self.line_12 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.ship1GridLayout.addWidget(self.line_12, 23, 0, 1, 6)
        self.ship1ArmorTypeTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ArmorTypeTitleLabel.setObjectName("ship1ArmorTypeTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1ArmorTypeTitleLabel, 8, 0, 1, 1)
        self.ship1NationLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1NationLabel.setObjectName("ship1NationLabel")
        self.ship1GridLayout.addWidget(self.ship1NationLabel, 4, 2, 1, 2)
        self.ship2AccuracyLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AccuracyLabel.setObjectName("ship2AccuracyLabel")
        self.ship1GridLayout.addWidget(self.ship2AccuracyLabel, 28, 4, 1, 2)
        self.ship1FirepowerLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1FirepowerLabel.setObjectName("ship1FirepowerLabel")
        self.ship1GridLayout.addWidget(self.ship1FirepowerLabel, 12, 2, 1, 2)
        self.line_15 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.ship1GridLayout.addWidget(self.line_15, 29, 0, 1, 6)
        self.line_5 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.ship1GridLayout.addWidget(self.line_5, 11, 0, 1, 6)
        self.ship1EvasionTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1EvasionTitleLabel.setObjectName("ship1EvasionTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1EvasionTitleLabel, 16, 0, 1, 1)
        self.ship1OxygenLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1OxygenLabel.setObjectName("ship1OxygenLabel")
        self.ship1GridLayout.addWidget(self.ship1OxygenLabel, 34, 2, 1, 2)
        self.ship1AmmunitionLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AmmunitionLabel.setObjectName("ship1AmmunitionLabel")
        self.ship1GridLayout.addWidget(self.ship1AmmunitionLabel, 36, 2, 1, 2)
        self.ship2OxygenLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2OxygenLabel.setObjectName("ship2OxygenLabel")
        self.ship1GridLayout.addWidget(self.ship2OxygenLabel, 34, 4, 1, 2)
        self.ship2NameLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ship2NameLabel.setObjectName("ship2NameLabel")
        self.ship1GridLayout.addWidget(self.ship2NameLabel, 0, 5, 1, 1)
        self.ship1HealthTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1HealthTitleLabel.setObjectName("ship1HealthTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1HealthTitleLabel, 10, 0, 1, 1)
        self.ship2CostLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2CostLabel.setObjectName("ship2CostLabel")
        self.ship1GridLayout.addWidget(self.ship2CostLabel, 32, 4, 1, 2)
        self.line_9 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.ship1GridLayout.addWidget(self.line_9, 19, 0, 1, 6)
        self.ship2LuckLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2LuckLabel.setObjectName("ship2LuckLabel")
        self.ship1GridLayout.addWidget(self.ship2LuckLabel, 24, 4, 1, 2)
        self.ship1AccuracyLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AccuracyLabel.setObjectName("ship1AccuracyLabel")
        self.ship1GridLayout.addWidget(self.ship1AccuracyLabel, 28, 2, 1, 2)
        self.ship2FirepowerLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2FirepowerLabel.setObjectName("ship2FirepowerLabel")
        self.ship1GridLayout.addWidget(self.ship2FirepowerLabel, 12, 4, 1, 2)
        self.line_6 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.ship1GridLayout.addWidget(self.line_6, 13, 0, 1, 6)
        self.ship1TypeLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1TypeLabel.setObjectName("ship1TypeLabel")
        self.ship1GridLayout.addWidget(self.ship1TypeLabel, 2, 2, 1, 2)
        self.ship2RarityLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2RarityLabel.setObjectName("ship2RarityLabel")
        self.ship1GridLayout.addWidget(self.ship2RarityLabel, 6, 4, 1, 2)
        self.line_10 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.ship1GridLayout.addWidget(self.line_10, 21, 0, 1, 6)
        self.ship1CostTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1CostTitleLabel.setObjectName("ship1CostTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1CostTitleLabel, 32, 0, 1, 1)
        self.line_18 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.ship1GridLayout.addWidget(self.line_18, 35, 0, 1, 6)
        self.ship1HealthLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1HealthLabel.setObjectName("ship1HealthLabel")
        self.ship1GridLayout.addWidget(self.ship1HealthLabel, 10, 2, 1, 2)
        self.ship2SpeedLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2SpeedLabel.setObjectName("ship2SpeedLabel")
        self.ship1GridLayout.addWidget(self.ship2SpeedLabel, 26, 4, 1, 2)
        self.ship1AntisubLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AntisubLabel.setObjectName("ship1AntisubLabel")
        self.ship1GridLayout.addWidget(self.ship1AntisubLabel, 30, 2, 1, 2)
        self.ship1ReloadTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ReloadTitleLabel.setObjectName("ship1ReloadTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1ReloadTitleLabel, 18, 0, 1, 1)
        self.line_14 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.ship1GridLayout.addWidget(self.line_14, 27, 0, 1, 6)
        self.ship1NameLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ship1NameLabel.setObjectName("ship1NameLabel")
        self.ship1GridLayout.addWidget(self.ship1NameLabel, 0, 3, 1, 1)
        self.ship1ArmorTypeLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ArmorTypeLabel.setObjectName("ship1ArmorTypeLabel")
        self.ship1GridLayout.addWidget(self.ship1ArmorTypeLabel, 8, 2, 1, 2)
        self.ship1ReloadLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ReloadLabel.setObjectName("ship1ReloadLabel")
        self.ship1GridLayout.addWidget(self.ship1ReloadLabel, 18, 2, 1, 2)
        self.ship1ImageLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ImageLabel.setObjectName("ship1ImageLabel")
        self.ship1GridLayout.addWidget(self.ship1ImageLabel, 0, 2, 1, 1)
        self.ship1LuckLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1LuckLabel.setObjectName("ship1LuckLabel")
        self.ship1GridLayout.addWidget(self.ship1LuckLabel, 24, 2, 1, 2)
        self.ship1RarityTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1RarityTitleLabel.setObjectName("ship1RarityTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1RarityTitleLabel, 6, 0, 1, 1)
        self.line_17 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.ship1GridLayout.addWidget(self.line_17, 33, 0, 1, 6)
        self.ship2AmmunitionLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AmmunitionLabel.setObjectName("ship2AmmunitionLabel")
        self.ship1GridLayout.addWidget(self.ship2AmmunitionLabel, 36, 4, 1, 2)
        self.line = QtWidgets.QFrame(ComparisonTwoShips)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ship1GridLayout.addWidget(self.line, 1, 0, 1, 6)
        self.ship1FirepowerTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1FirepowerTitleLabel.setObjectName("ship1FirepowerTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1FirepowerTitleLabel, 12, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.ship1GridLayout.addWidget(self.line_13, 25, 0, 1, 6)
        self.ship2TypeLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2TypeLabel.setObjectName("ship2TypeLabel")
        self.ship1GridLayout.addWidget(self.ship2TypeLabel, 2, 4, 1, 2)
        self.ship1NationTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1NationTitleLabel.setObjectName("ship1NationTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1NationTitleLabel, 4, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.ship1GridLayout.addWidget(self.line_2, 3, 0, 1, 6)
        self.ship1TorpedoTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1TorpedoTitleLabel.setObjectName("ship1TorpedoTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1TorpedoTitleLabel, 14, 0, 1, 1)
        self.ship1EvasionLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1EvasionLabel.setObjectName("ship1EvasionLabel")
        self.ship1GridLayout.addWidget(self.ship1EvasionLabel, 16, 2, 1, 2)
        self.ship2ArmorTypeLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2ArmorTypeLabel.setObjectName("ship2ArmorTypeLabel")
        self.ship1GridLayout.addWidget(self.ship2ArmorTypeLabel, 8, 4, 1, 2)
        self.ship2AviationLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AviationLabel.setObjectName("ship2AviationLabel")
        self.ship1GridLayout.addWidget(self.ship2AviationLabel, 22, 4, 1, 2)
        self.ship2TorpedoLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2TorpedoLabel.setObjectName("ship2TorpedoLabel")
        self.ship1GridLayout.addWidget(self.ship2TorpedoLabel, 14, 4, 1, 2)
        self.line_3 = QtWidgets.QFrame(ComparisonTwoShips)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.ship1GridLayout.addWidget(self.line_3, 5, 0, 1, 6)
        self.ship1RarityLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1RarityLabel.setObjectName("ship1RarityLabel")
        self.ship1GridLayout.addWidget(self.ship1RarityLabel, 6, 2, 1, 2)
        self.ship1AntiairTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AntiairTitleLabel.setObjectName("ship1AntiairTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AntiairTitleLabel, 20, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ship1GridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.ship1GridLayout, 2, 1, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        self.levelLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.levelLabel.setObjectName("levelLabel")
        self.gridLayout.addWidget(self.levelLabel, 0, 1, 1, 1)

        self.retranslateUi(ComparisonTwoShips)
        QtCore.QMetaObject.connectSlotsByName(ComparisonTwoShips)

    def retranslateUi(self, ComparisonTwoShips):
        ComparisonTwoShips.setWindowTitle(QtWidgets.QApplication.translate("ComparisonTwoShips", "Form", None, -1))
        self.levelComboBox.setItemText(0, QtWidgets.QApplication.translate("ComparisonTwoShips", "1", None, -1))
        self.levelComboBox.setItemText(1, QtWidgets.QApplication.translate("ComparisonTwoShips", "100", None, -1))
        self.levelComboBox.setItemText(2, QtWidgets.QApplication.translate("ComparisonTwoShips", "120", None, -1))
        self.ship1AmmunitionTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Ammunition:", None, -1))
        self.ship2ImageLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Image2", None, -1))
        self.ship1LuckTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Luck:", None, -1))
        self.ship2AntiairLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-air2", None, -1))
        self.ship1TypeTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Type: ", None, -1))
        self.ship2NationLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Nation2", None, -1))
        self.ship1AccuracyTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Accuracy:", None, -1))
        self.ship1SpeedLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Speed1", None, -1))
        self.ship2HealthLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Health2", None, -1))
        self.ship1AviationLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Aviation1", None, -1))
        self.ship1SpeedTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Speed:", None, -1))
        self.ship1AntisubTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-sub:", None, -1))
        self.ship1TorpedoLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Torpedo1", None, -1))
        self.ship1AviationTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Aviation:", None, -1))
        self.ship1AntiairLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-air1", None, -1))
        self.ship2ReloadLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Reload2", None, -1))
        self.ship1OxygenTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Oxygen:", None, -1))
        self.ship2EvasionLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Evasion2", None, -1))
        self.ship2AntisubLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Antisub2", None, -1))
        self.ship1CostLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Cost1", None, -1))
        self.ship1ArmorTypeTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Armor Type:", None, -1))
        self.ship1NationLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Nation1", None, -1))
        self.ship2AccuracyLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Accuracy2", None, -1))
        self.ship1FirepowerLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Firepower1", None, -1))
        self.ship1EvasionTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Evasion:", None, -1))
        self.ship1OxygenLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Oxygen1", None, -1))
        self.ship1AmmunitionLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Ammunition1", None, -1))
        self.ship2OxygenLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Oxygen2", None, -1))
        self.ship2NameLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Name2", None, -1))
        self.ship1HealthTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Health:", None, -1))
        self.ship2CostLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Cost2", None, -1))
        self.ship2LuckLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Luck2", None, -1))
        self.ship1AccuracyLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Accuracy1", None, -1))
        self.ship2FirepowerLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Firepower2", None, -1))
        self.ship1TypeLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Type1", None, -1))
        self.ship2RarityLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Rarity2", None, -1))
        self.ship1CostTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Cost:", None, -1))
        self.ship1HealthLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Health1", None, -1))
        self.ship2SpeedLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Speed2", None, -1))
        self.ship1AntisubLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Antisub1", None, -1))
        self.ship1ReloadTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Reload:", None, -1))
        self.ship1NameLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Name1", None, -1))
        self.ship1ArmorTypeLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "ArmorType1", None, -1))
        self.ship1ReloadLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Reload1", None, -1))
        self.ship1ImageLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Image1", None, -1))
        self.ship1LuckLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Luck1", None, -1))
        self.ship1RarityTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Rarity:", None, -1))
        self.ship2AmmunitionLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Ammunition2", None, -1))
        self.ship1FirepowerTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Firepower:", None, -1))
        self.ship2TypeLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Type2", None, -1))
        self.ship1NationTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Nation:", None, -1))
        self.ship1TorpedoTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Torpedo:", None, -1))
        self.ship1EvasionLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Evasion1", None, -1))
        self.ship2ArmorTypeLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "ArmorType2", None, -1))
        self.ship2AviationLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Aviation2", None, -1))
        self.ship2TorpedoLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Torpedo2", None, -1))
        self.ship1RarityLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Rarity1", None, -1))
        self.ship1AntiairTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-air:", None, -1))
        self.levelLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Level:", None, -1))

