# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comparison_two_ships.ui',
# licensing of 'comparison_two_ships.ui' applies.
#
# Created: Tue Dec  3 18:17:16 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ComparisonTwoShips(object):
    def setupUi(self, ComparisonTwoShips):
        ComparisonTwoShips.setObjectName("ComparisonTwoShips")
        ComparisonTwoShips.resize(400, 400)
        self.gridLayout = QtWidgets.QGridLayout(ComparisonTwoShips)
        self.gridLayout.setObjectName("gridLayout")
        self.ship1GridLayout = QtWidgets.QGridLayout()
        self.ship1GridLayout.setObjectName("ship1GridLayout")
        self.ship1AntisubTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AntisubTitleLabel.setObjectName("ship1AntisubTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AntisubTitleLabel, 15, 0, 1, 1)
        self.ship1TorpedoTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1TorpedoTitleLabel.setObjectName("ship1TorpedoTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1TorpedoTitleLabel, 7, 0, 1, 1)
        self.ship1FirepowerTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1FirepowerTitleLabel.setObjectName("ship1FirepowerTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1FirepowerTitleLabel, 6, 0, 1, 1)
        self.ship1TypeLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1TypeLabel.setObjectName("ship1TypeLabel")
        self.ship1GridLayout.addWidget(self.ship1TypeLabel, 1, 1, 1, 1)
        self.ship1NationLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1NationLabel.setObjectName("ship1NationLabel")
        self.ship1GridLayout.addWidget(self.ship1NationLabel, 2, 1, 1, 1)
        self.ship1ReloadLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ReloadLabel.setObjectName("ship1ReloadLabel")
        self.ship1GridLayout.addWidget(self.ship1ReloadLabel, 9, 1, 1, 1)
        self.ship1CostLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1CostLabel.setObjectName("ship1CostLabel")
        self.ship1GridLayout.addWidget(self.ship1CostLabel, 16, 1, 1, 1)
        self.ship1RarityTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1RarityTitleLabel.setObjectName("ship1RarityTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1RarityTitleLabel, 3, 0, 1, 1)
        self.ship1LuckLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1LuckLabel.setObjectName("ship1LuckLabel")
        self.ship1GridLayout.addWidget(self.ship1LuckLabel, 12, 1, 1, 1)
        self.ship1ArmorTypeTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ArmorTypeTitleLabel.setObjectName("ship1ArmorTypeTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1ArmorTypeTitleLabel, 4, 0, 1, 1)
        self.ship1CostTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1CostTitleLabel.setObjectName("ship1CostTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1CostTitleLabel, 16, 0, 1, 1)
        self.ship1AviationTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AviationTitleLabel.setObjectName("ship1AviationTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AviationTitleLabel, 11, 0, 1, 1)
        self.ship1FirepowerLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1FirepowerLabel.setObjectName("ship1FirepowerLabel")
        self.ship1GridLayout.addWidget(self.ship1FirepowerLabel, 6, 1, 1, 1)
        self.ship1AntiairTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AntiairTitleLabel.setObjectName("ship1AntiairTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AntiairTitleLabel, 10, 0, 1, 1)
        self.ship1OxygenLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1OxygenLabel.setObjectName("ship1OxygenLabel")
        self.ship1GridLayout.addWidget(self.ship1OxygenLabel, 17, 1, 1, 1)
        self.ship1NationTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1NationTitleLabel.setObjectName("ship1NationTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1NationTitleLabel, 2, 0, 1, 1)
        self.ship1AviationLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AviationLabel.setObjectName("ship1AviationLabel")
        self.ship1GridLayout.addWidget(self.ship1AviationLabel, 11, 1, 1, 1)
        self.ship1HealthLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1HealthLabel.setObjectName("ship1HealthLabel")
        self.ship1GridLayout.addWidget(self.ship1HealthLabel, 5, 1, 1, 1)
        self.ship1EvasionTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1EvasionTitleLabel.setObjectName("ship1EvasionTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1EvasionTitleLabel, 8, 0, 1, 1)
        self.ship1AntisubLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AntisubLabel.setObjectName("ship1AntisubLabel")
        self.ship1GridLayout.addWidget(self.ship1AntisubLabel, 15, 1, 1, 1)
        self.ship1SpeedTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1SpeedTitleLabel.setObjectName("ship1SpeedTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1SpeedTitleLabel, 13, 0, 1, 1)
        self.ship1OxygenTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1OxygenTitleLabel.setObjectName("ship1OxygenTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1OxygenTitleLabel, 17, 0, 1, 1)
        self.ship1ArmorTypeLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ArmorTypeLabel.setObjectName("ship1ArmorTypeLabel")
        self.ship1GridLayout.addWidget(self.ship1ArmorTypeLabel, 4, 1, 1, 1)
        self.ship1LuckTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1LuckTitleLabel.setObjectName("ship1LuckTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1LuckTitleLabel, 12, 0, 1, 1)
        self.ship1TypeTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1TypeTitleLabel.setObjectName("ship1TypeTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1TypeTitleLabel, 1, 0, 1, 1)
        self.ship1AntiairLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AntiairLabel.setObjectName("ship1AntiairLabel")
        self.ship1GridLayout.addWidget(self.ship1AntiairLabel, 10, 1, 1, 1)
        self.ship1NameLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ship1NameLabel.setObjectName("ship1NameLabel")
        self.ship1GridLayout.addWidget(self.ship1NameLabel, 0, 0, 1, 2)
        self.ship1TorpedoLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1TorpedoLabel.setObjectName("ship1TorpedoLabel")
        self.ship1GridLayout.addWidget(self.ship1TorpedoLabel, 7, 1, 1, 1)
        self.ship1ReloadTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1ReloadTitleLabel.setObjectName("ship1ReloadTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1ReloadTitleLabel, 9, 0, 1, 1)
        self.ship1AccuracyLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AccuracyLabel.setObjectName("ship1AccuracyLabel")
        self.ship1GridLayout.addWidget(self.ship1AccuracyLabel, 14, 1, 1, 1)
        self.ship1HealthTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1HealthTitleLabel.setObjectName("ship1HealthTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1HealthTitleLabel, 5, 0, 1, 1)
        self.ship1EvasionLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1EvasionLabel.setObjectName("ship1EvasionLabel")
        self.ship1GridLayout.addWidget(self.ship1EvasionLabel, 8, 1, 1, 1)
        self.ship1AccuracyTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AccuracyTitleLabel.setObjectName("ship1AccuracyTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AccuracyTitleLabel, 14, 0, 1, 1)
        self.ship1RarityLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1RarityLabel.setObjectName("ship1RarityLabel")
        self.ship1GridLayout.addWidget(self.ship1RarityLabel, 3, 1, 1, 1)
        self.ship1SpeedLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1SpeedLabel.setObjectName("ship1SpeedLabel")
        self.ship1GridLayout.addWidget(self.ship1SpeedLabel, 13, 1, 1, 1)
        self.ship1AmmunitionTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AmmunitionTitleLabel.setObjectName("ship1AmmunitionTitleLabel")
        self.ship1GridLayout.addWidget(self.ship1AmmunitionTitleLabel, 18, 0, 1, 1)
        self.ship1AmmunitionLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship1AmmunitionLabel.setObjectName("ship1AmmunitionLabel")
        self.ship1GridLayout.addWidget(self.ship1AmmunitionLabel, 18, 1, 1, 1)
        self.gridLayout.addLayout(self.ship1GridLayout, 1, 1, 1, 1)
        self.levelComboBox = QtWidgets.QComboBox(ComparisonTwoShips)
        self.levelComboBox.setObjectName("levelComboBox")
        self.levelComboBox.addItem("")
        self.levelComboBox.addItem("")
        self.levelComboBox.addItem("")
        self.gridLayout.addWidget(self.levelComboBox, 0, 2, 1, 1)
        self.ship2GridLayout = QtWidgets.QGridLayout()
        self.ship2GridLayout.setObjectName("ship2GridLayout")
        self.ship2NationTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2NationTitleLabel.setObjectName("ship2NationTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2NationTitleLabel, 2, 0, 1, 1)
        self.ship2LuckTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2LuckTitleLabel.setObjectName("ship2LuckTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2LuckTitleLabel, 12, 0, 1, 1)
        self.ship2TypeLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2TypeLabel.setObjectName("ship2TypeLabel")
        self.ship2GridLayout.addWidget(self.ship2TypeLabel, 1, 1, 1, 1)
        self.ship2HealthTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2HealthTitleLabel.setObjectName("ship2HealthTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2HealthTitleLabel, 5, 0, 1, 1)
        self.ship2HealthLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2HealthLabel.setObjectName("ship2HealthLabel")
        self.ship2GridLayout.addWidget(self.ship2HealthLabel, 5, 1, 1, 1)
        self.ship2RarityTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2RarityTitleLabel.setObjectName("ship2RarityTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2RarityTitleLabel, 3, 0, 1, 1)
        self.ship2AntisubLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AntisubLabel.setObjectName("ship2AntisubLabel")
        self.ship2GridLayout.addWidget(self.ship2AntisubLabel, 15, 1, 1, 1)
        self.ship2TorpedoTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2TorpedoTitleLabel.setObjectName("ship2TorpedoTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2TorpedoTitleLabel, 7, 0, 1, 1)
        self.ship2LuckLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2LuckLabel.setObjectName("ship2LuckLabel")
        self.ship2GridLayout.addWidget(self.ship2LuckLabel, 12, 1, 1, 1)
        self.ship2CostLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2CostLabel.setObjectName("ship2CostLabel")
        self.ship2GridLayout.addWidget(self.ship2CostLabel, 16, 1, 1, 1)
        self.ship2EvasionLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2EvasionLabel.setObjectName("ship2EvasionLabel")
        self.ship2GridLayout.addWidget(self.ship2EvasionLabel, 8, 1, 1, 1)
        self.ship2AntiairLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AntiairLabel.setObjectName("ship2AntiairLabel")
        self.ship2GridLayout.addWidget(self.ship2AntiairLabel, 10, 1, 1, 1)
        self.ship2AviationTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AviationTitleLabel.setObjectName("ship2AviationTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2AviationTitleLabel, 11, 0, 1, 1)
        self.ship2ArmorTypeLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2ArmorTypeLabel.setObjectName("ship2ArmorTypeLabel")
        self.ship2GridLayout.addWidget(self.ship2ArmorTypeLabel, 4, 1, 1, 1)
        self.ship2SpeedTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2SpeedTitleLabel.setObjectName("ship2SpeedTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2SpeedTitleLabel, 13, 0, 1, 1)
        self.ship2SpeedLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2SpeedLabel.setObjectName("ship2SpeedLabel")
        self.ship2GridLayout.addWidget(self.ship2SpeedLabel, 13, 1, 1, 1)
        self.ship2FirepowerTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2FirepowerTitleLabel.setObjectName("ship2FirepowerTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2FirepowerTitleLabel, 6, 0, 1, 1)
        self.ship2EvasionTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2EvasionTitleLabel.setObjectName("ship2EvasionTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2EvasionTitleLabel, 8, 0, 1, 1)
        self.ship2OxygenLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2OxygenLabel.setObjectName("ship2OxygenLabel")
        self.ship2GridLayout.addWidget(self.ship2OxygenLabel, 17, 1, 1, 1)
        self.ship2NationLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2NationLabel.setObjectName("ship2NationLabel")
        self.ship2GridLayout.addWidget(self.ship2NationLabel, 2, 1, 1, 1)
        self.ship2AntiairTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AntiairTitleLabel.setObjectName("ship2AntiairTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2AntiairTitleLabel, 10, 0, 1, 1)
        self.ship2ArmorTypeTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2ArmorTypeTitleLabel.setObjectName("ship2ArmorTypeTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2ArmorTypeTitleLabel, 4, 0, 1, 1)
        self.ship2AccuracyTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AccuracyTitleLabel.setObjectName("ship2AccuracyTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2AccuracyTitleLabel, 14, 0, 1, 1)
        self.ship2TorpedoLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2TorpedoLabel.setObjectName("ship2TorpedoLabel")
        self.ship2GridLayout.addWidget(self.ship2TorpedoLabel, 7, 1, 1, 1)
        self.ship2NameLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ship2NameLabel.setObjectName("ship2NameLabel")
        self.ship2GridLayout.addWidget(self.ship2NameLabel, 0, 0, 1, 2)
        self.ship2TypeTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2TypeTitleLabel.setObjectName("ship2TypeTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2TypeTitleLabel, 1, 0, 1, 1)
        self.ship2AviationLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AviationLabel.setObjectName("ship2AviationLabel")
        self.ship2GridLayout.addWidget(self.ship2AviationLabel, 11, 1, 1, 1)
        self.ship2FirepowerLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2FirepowerLabel.setObjectName("ship2FirepowerLabel")
        self.ship2GridLayout.addWidget(self.ship2FirepowerLabel, 6, 1, 1, 1)
        self.ship2CostTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2CostTitleLabel.setObjectName("ship2CostTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2CostTitleLabel, 16, 0, 1, 1)
        self.ship2OxygenTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2OxygenTitleLabel.setObjectName("ship2OxygenTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2OxygenTitleLabel, 17, 0, 1, 1)
        self.ship2ReloadTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2ReloadTitleLabel.setObjectName("ship2ReloadTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2ReloadTitleLabel, 9, 0, 1, 1)
        self.ship2AntisubTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AntisubTitleLabel.setObjectName("ship2AntisubTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2AntisubTitleLabel, 15, 0, 1, 1)
        self.ship2RarityLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2RarityLabel.setObjectName("ship2RarityLabel")
        self.ship2GridLayout.addWidget(self.ship2RarityLabel, 3, 1, 1, 1)
        self.ship2AccuracyLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AccuracyLabel.setObjectName("ship2AccuracyLabel")
        self.ship2GridLayout.addWidget(self.ship2AccuracyLabel, 14, 1, 1, 1)
        self.ship2ReloadLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2ReloadLabel.setObjectName("ship2ReloadLabel")
        self.ship2GridLayout.addWidget(self.ship2ReloadLabel, 9, 1, 1, 1)
        self.ship2AmmunitionTitleLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AmmunitionTitleLabel.setObjectName("ship2AmmunitionTitleLabel")
        self.ship2GridLayout.addWidget(self.ship2AmmunitionTitleLabel, 18, 0, 1, 1)
        self.ship2AmmunitionLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.ship2AmmunitionLabel.setObjectName("ship2AmmunitionLabel")
        self.ship2GridLayout.addWidget(self.ship2AmmunitionLabel, 18, 1, 1, 1)
        self.gridLayout.addLayout(self.ship2GridLayout, 1, 2, 1, 1)
        self.levelLabel = QtWidgets.QLabel(ComparisonTwoShips)
        self.levelLabel.setObjectName("levelLabel")
        self.gridLayout.addWidget(self.levelLabel, 0, 1, 1, 1)

        self.retranslateUi(ComparisonTwoShips)
        QtCore.QMetaObject.connectSlotsByName(ComparisonTwoShips)

    def retranslateUi(self, ComparisonTwoShips):
        ComparisonTwoShips.setWindowTitle(QtWidgets.QApplication.translate("ComparisonTwoShips", "Form", None, -1))
        self.ship1AntisubTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-sub:", None, -1))
        self.ship1TorpedoTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Torpedo:", None, -1))
        self.ship1FirepowerTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Firepower:", None, -1))
        self.ship1TypeLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Type1", None, -1))
        self.ship1NationLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Nation1", None, -1))
        self.ship1ReloadLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Reload1", None, -1))
        self.ship1CostLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Cost1", None, -1))
        self.ship1RarityTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Rarity:", None, -1))
        self.ship1LuckLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Luck1", None, -1))
        self.ship1ArmorTypeTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Armor Type", None, -1))
        self.ship1CostTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Cost:", None, -1))
        self.ship1AviationTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Aviation:", None, -1))
        self.ship1FirepowerLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Firepower1", None, -1))
        self.ship1AntiairTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-air:", None, -1))
        self.ship1OxygenLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Oxygen1", None, -1))
        self.ship1NationTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Nation:", None, -1))
        self.ship1AviationLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Aviation1", None, -1))
        self.ship1HealthLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Health1", None, -1))
        self.ship1EvasionTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Evasion:", None, -1))
        self.ship1AntisubLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Antisub1", None, -1))
        self.ship1SpeedTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Speed:", None, -1))
        self.ship1OxygenTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Oxygen:", None, -1))
        self.ship1ArmorTypeLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "ArmorType1", None, -1))
        self.ship1LuckTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Luck:", None, -1))
        self.ship1TypeTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Type: ", None, -1))
        self.ship1AntiairLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-air1", None, -1))
        self.ship1NameLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Name1", None, -1))
        self.ship1TorpedoLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Torpedo1", None, -1))
        self.ship1ReloadTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Reload:", None, -1))
        self.ship1AccuracyLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Accuracy1", None, -1))
        self.ship1HealthTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Health:", None, -1))
        self.ship1EvasionLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Evasion1", None, -1))
        self.ship1AccuracyTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Accuracy:", None, -1))
        self.ship1RarityLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Rarity1", None, -1))
        self.ship1SpeedLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Speed1", None, -1))
        self.ship1AmmunitionTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Ammunition:", None, -1))
        self.ship1AmmunitionLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Ammunition1", None, -1))
        self.levelComboBox.setItemText(0, QtWidgets.QApplication.translate("ComparisonTwoShips", "1", None, -1))
        self.levelComboBox.setItemText(1, QtWidgets.QApplication.translate("ComparisonTwoShips", "100", None, -1))
        self.levelComboBox.setItemText(2, QtWidgets.QApplication.translate("ComparisonTwoShips", "120", None, -1))
        self.ship2NationTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Nation:", None, -1))
        self.ship2LuckTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Luck:", None, -1))
        self.ship2TypeLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Type2", None, -1))
        self.ship2HealthTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Health:", None, -1))
        self.ship2HealthLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Health2", None, -1))
        self.ship2RarityTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Rarity:", None, -1))
        self.ship2AntisubLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Antisub2", None, -1))
        self.ship2TorpedoTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Torpedo:", None, -1))
        self.ship2LuckLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Luck2", None, -1))
        self.ship2CostLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Cost2", None, -1))
        self.ship2EvasionLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Evasion2", None, -1))
        self.ship2AntiairLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-air2", None, -1))
        self.ship2AviationTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Aviation:", None, -1))
        self.ship2ArmorTypeLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "ArmorType2", None, -1))
        self.ship2SpeedTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Speed:", None, -1))
        self.ship2SpeedLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Speed2", None, -1))
        self.ship2FirepowerTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Firepower:", None, -1))
        self.ship2EvasionTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Evasion:", None, -1))
        self.ship2OxygenLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Oxygen2", None, -1))
        self.ship2NationLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Nation2", None, -1))
        self.ship2AntiairTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-air:", None, -1))
        self.ship2ArmorTypeTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Armor Type", None, -1))
        self.ship2AccuracyTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Accuracy:", None, -1))
        self.ship2TorpedoLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Torpedo2", None, -1))
        self.ship2NameLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Name2", None, -1))
        self.ship2TypeTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Type:", None, -1))
        self.ship2AviationLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Aviation2", None, -1))
        self.ship2FirepowerLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Firepower2", None, -1))
        self.ship2CostTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Cost:", None, -1))
        self.ship2OxygenTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Oxygen:", None, -1))
        self.ship2ReloadTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Reload:", None, -1))
        self.ship2AntisubTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Anti-sub:", None, -1))
        self.ship2RarityLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Rarity2", None, -1))
        self.ship2AccuracyLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Accuracy2", None, -1))
        self.ship2ReloadLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Reload2", None, -1))
        self.ship2AmmunitionTitleLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Ammunition:", None, -1))
        self.ship2AmmunitionLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Ammunition2", None, -1))
        self.levelLabel.setText(QtWidgets.QApplication.translate("ComparisonTwoShips", "Level:", None, -1))

