# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\module_retrofit.ui',
# licensing of '.\module_retrofit.ui' applies.
#
# Created: Mon Dec  9 18:26:59 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ModuleRetrofit(object):
    def setupUi(self, ModuleRetrofit):
        ModuleRetrofit.setObjectName("ModuleRetrofit")
        ModuleRetrofit.resize(560, 403)
        self.gridLayout = QtWidgets.QGridLayout(ModuleRetrofit)
        self.gridLayout.setObjectName("gridLayout")
        self.destroyersT2NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.destroyersT2NbLabel.setObjectName("destroyersT2NbLabel")
        self.gridLayout.addWidget(self.destroyersT2NbLabel, 2, 0, 1, 1)
        self.battleshipsT1IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.battleshipsT1IconLabel.setObjectName("battleshipsT1IconLabel")
        self.gridLayout.addWidget(self.battleshipsT1IconLabel, 1, 5, 1, 1)
        self.carriersT1NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.carriersT1NbLabel.setObjectName("carriersT1NbLabel")
        self.gridLayout.addWidget(self.carriersT1NbLabel, 1, 6, 1, 1)
        self.destroyersT1NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.destroyersT1NbLabel.setObjectName("destroyersT1NbLabel")
        self.gridLayout.addWidget(self.destroyersT1NbLabel, 1, 0, 1, 1)
        self.destroyersT3NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.destroyersT3NbLabel.setObjectName("destroyersT3NbLabel")
        self.gridLayout.addWidget(self.destroyersT3NbLabel, 3, 0, 1, 1)
        self.destroyersLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.destroyersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.destroyersLabel.setObjectName("destroyersLabel")
        self.gridLayout.addWidget(self.destroyersLabel, 0, 0, 1, 2)
        self.cruisersT1IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.cruisersT1IconLabel.setObjectName("cruisersT1IconLabel")
        self.gridLayout.addWidget(self.cruisersT1IconLabel, 1, 3, 1, 1)
        self.destroyersT1IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.destroyersT1IconLabel.setTextFormat(QtCore.Qt.RichText)
        self.destroyersT1IconLabel.setObjectName("destroyersT1IconLabel")
        self.gridLayout.addWidget(self.destroyersT1IconLabel, 1, 1, 1, 1)
        self.destroyersT3IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.destroyersT3IconLabel.setObjectName("destroyersT3IconLabel")
        self.gridLayout.addWidget(self.destroyersT3IconLabel, 3, 1, 1, 1)
        self.battleshipsT1NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.battleshipsT1NbLabel.setObjectName("battleshipsT1NbLabel")
        self.gridLayout.addWidget(self.battleshipsT1NbLabel, 1, 4, 1, 1)
        self.cruisersT1NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.cruisersT1NbLabel.setObjectName("cruisersT1NbLabel")
        self.gridLayout.addWidget(self.cruisersT1NbLabel, 1, 2, 1, 1)
        self.cruisersLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.cruisersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cruisersLabel.setObjectName("cruisersLabel")
        self.gridLayout.addWidget(self.cruisersLabel, 0, 2, 1, 2)
        self.destroyersT2IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.destroyersT2IconLabel.setObjectName("destroyersT2IconLabel")
        self.gridLayout.addWidget(self.destroyersT2IconLabel, 2, 1, 1, 1)
        self.carriersT1IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.carriersT1IconLabel.setObjectName("carriersT1IconLabel")
        self.gridLayout.addWidget(self.carriersT1IconLabel, 1, 7, 1, 1)
        self.battleshipsLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.battleshipsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.battleshipsLabel.setObjectName("battleshipsLabel")
        self.gridLayout.addWidget(self.battleshipsLabel, 0, 4, 1, 2)
        self.carriersLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.carriersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.carriersLabel.setObjectName("carriersLabel")
        self.gridLayout.addWidget(self.carriersLabel, 0, 6, 1, 2)
        self.cruisersT2NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.cruisersT2NbLabel.setObjectName("cruisersT2NbLabel")
        self.gridLayout.addWidget(self.cruisersT2NbLabel, 2, 2, 1, 1)
        self.cruisersT3NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.cruisersT3NbLabel.setObjectName("cruisersT3NbLabel")
        self.gridLayout.addWidget(self.cruisersT3NbLabel, 3, 2, 1, 1)
        self.cruisersT2IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.cruisersT2IconLabel.setObjectName("cruisersT2IconLabel")
        self.gridLayout.addWidget(self.cruisersT2IconLabel, 2, 3, 1, 1)
        self.cruisersT3IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.cruisersT3IconLabel.setObjectName("cruisersT3IconLabel")
        self.gridLayout.addWidget(self.cruisersT3IconLabel, 3, 3, 1, 1)
        self.battleshipsT2NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.battleshipsT2NbLabel.setObjectName("battleshipsT2NbLabel")
        self.gridLayout.addWidget(self.battleshipsT2NbLabel, 2, 4, 1, 1)
        self.battleshipsT3NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.battleshipsT3NbLabel.setObjectName("battleshipsT3NbLabel")
        self.gridLayout.addWidget(self.battleshipsT3NbLabel, 3, 4, 1, 1)
        self.battleshipsT2IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.battleshipsT2IconLabel.setObjectName("battleshipsT2IconLabel")
        self.gridLayout.addWidget(self.battleshipsT2IconLabel, 2, 5, 1, 1)
        self.battleshipsT3IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.battleshipsT3IconLabel.setObjectName("battleshipsT3IconLabel")
        self.gridLayout.addWidget(self.battleshipsT3IconLabel, 3, 5, 1, 1)
        self.carriersT2NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.carriersT2NbLabel.setObjectName("carriersT2NbLabel")
        self.gridLayout.addWidget(self.carriersT2NbLabel, 2, 6, 1, 1)
        self.carriersT2IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.carriersT2IconLabel.setObjectName("carriersT2IconLabel")
        self.gridLayout.addWidget(self.carriersT2IconLabel, 2, 7, 1, 1)
        self.carriersT3NbLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.carriersT3NbLabel.setObjectName("carriersT3NbLabel")
        self.gridLayout.addWidget(self.carriersT3NbLabel, 3, 6, 1, 1)
        self.carriersT3IconLabel = QtWidgets.QLabel(ModuleRetrofit)
        self.carriersT3IconLabel.setObjectName("carriersT3IconLabel")
        self.gridLayout.addWidget(self.carriersT3IconLabel, 3, 7, 1, 1)

        self.retranslateUi(ModuleRetrofit)
        QtCore.QMetaObject.connectSlotsByName(ModuleRetrofit)

    def retranslateUi(self, ModuleRetrofit):
        ModuleRetrofit.setWindowTitle(QtWidgets.QApplication.translate("ModuleRetrofit", "Form", None, -1))
        self.destroyersT2NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T2Nb", None, -1))
        self.battleshipsT1IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "BBT1Icon", None, -1))
        self.carriersT1NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T1Nb", None, -1))
        self.destroyersT1NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T1Nb", None, -1))
        self.destroyersT3NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T3Nb", None, -1))
        self.destroyersLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "Destroyers", None, -1))
        self.cruisersT1IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "CLT1Icon", None, -1))
        self.destroyersT1IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "DDT1Icon", None, -1))
        self.destroyersT3IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "DDT3Icon", None, -1))
        self.battleshipsT1NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T1Nb", None, -1))
        self.cruisersT1NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T1Nb", None, -1))
        self.cruisersLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "Cruisers", None, -1))
        self.destroyersT2IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "DDT2Icon", None, -1))
        self.carriersT1IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "CVT1Icon", None, -1))
        self.battleshipsLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "Battleships", None, -1))
        self.carriersLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "Carriers", None, -1))
        self.cruisersT2NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T2Nb", None, -1))
        self.cruisersT3NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T3Nb", None, -1))
        self.cruisersT2IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "CLT2Icon", None, -1))
        self.cruisersT3IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "CLT3Icon", None, -1))
        self.battleshipsT2NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T2Nb", None, -1))
        self.battleshipsT3NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T3Nb", None, -1))
        self.battleshipsT2IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "BBT2Icon", None, -1))
        self.battleshipsT3IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "BBT3Icon", None, -1))
        self.carriersT2NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T2Nb", None, -1))
        self.carriersT2IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "CVT2Icon", None, -1))
        self.carriersT3NbLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "T3Nb", None, -1))
        self.carriersT3IconLabel.setText(QtWidgets.QApplication.translate("ModuleRetrofit", "CVT3Icon", None, -1))

