# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'research_widget.ui',
# licensing of 'research_widget.ui' applies.
#
# Created: Wed Jan 15 16:23:29 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ResearchWidget(object):
    def setupUi(self, ResearchWidget):
        ResearchWidget.setObjectName("ResearchWidget")
        ResearchWidget.resize(765, 294)
        self.gridLayout = QtWidgets.QGridLayout(ResearchWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.shipIconLabel = QtWidgets.QLabel(ResearchWidget)
        self.shipIconLabel.setObjectName("shipIconLabel")
        self.gridLayout.addWidget(self.shipIconLabel, 1, 0, 3, 1)
        self.fateSimulationPhaseLabel = QtWidgets.QLabel(ResearchWidget)
        self.fateSimulationPhaseLabel.setObjectName("fateSimulationPhaseLabel")
        self.gridLayout.addWidget(self.fateSimulationPhaseLabel, 3, 2, 1, 1)
        self.currentBpSpinBox = QtWidgets.QSpinBox(ResearchWidget)
        self.currentBpSpinBox.setMaximum(9999)
        self.currentBpSpinBox.setObjectName("currentBpSpinBox")
        self.gridLayout.addWidget(self.currentBpSpinBox, 2, 4, 1, 1)
        self.currentBpLabel = QtWidgets.QLabel(ResearchWidget)
        self.currentBpLabel.setObjectName("currentBpLabel")
        self.gridLayout.addWidget(self.currentBpLabel, 2, 2, 1, 1)
        self.strengthenLevelTableWidget = QtWidgets.QTableWidget(ResearchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strengthenLevelTableWidget.sizePolicy().hasHeightForWidth())
        self.strengthenLevelTableWidget.setSizePolicy(sizePolicy)
        self.strengthenLevelTableWidget.setMinimumSize(QtCore.QSize(720, 55))
        self.strengthenLevelTableWidget.setBaseSize(QtCore.QSize(0, 0))
        self.strengthenLevelTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.strengthenLevelTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.strengthenLevelTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.strengthenLevelTableWidget.setRowCount(1)
        self.strengthenLevelTableWidget.setColumnCount(6)
        self.strengthenLevelTableWidget.setObjectName("strengthenLevelTableWidget")
        self.strengthenLevelTableWidget.setColumnCount(6)
        self.strengthenLevelTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.strengthenLevelTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.strengthenLevelTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.strengthenLevelTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.strengthenLevelTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.strengthenLevelTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.strengthenLevelTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.strengthenLevelTableWidget.setHorizontalHeaderItem(5, item)
        self.strengthenLevelTableWidget.horizontalHeader().setVisible(True)
        self.strengthenLevelTableWidget.verticalHeader().setVisible(True)
        self.gridLayout.addWidget(self.strengthenLevelTableWidget, 6, 0, 1, 6)
        self.researchLevelLabel = QtWidgets.QLabel(ResearchWidget)
        self.researchLevelLabel.setObjectName("researchLevelLabel")
        self.gridLayout.addWidget(self.researchLevelLabel, 1, 2, 1, 1)
        self.bpNeededPerLevelTitleLabel = QtWidgets.QLabel(ResearchWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.bpNeededPerLevelTitleLabel.setFont(font)
        self.bpNeededPerLevelTitleLabel.setObjectName("bpNeededPerLevelTitleLabel")
        self.gridLayout.addWidget(self.bpNeededPerLevelTitleLabel, 5, 0, 1, 6)
        self.researchLevelSpinBox = QtWidgets.QSpinBox(ResearchWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.researchLevelSpinBox.sizePolicy().hasHeightForWidth())
        self.researchLevelSpinBox.setSizePolicy(sizePolicy)
        self.researchLevelSpinBox.setMinimum(1)
        self.researchLevelSpinBox.setMaximum(30)
        self.researchLevelSpinBox.setObjectName("researchLevelSpinBox")
        self.gridLayout.addWidget(self.researchLevelSpinBox, 1, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 1)
        self.fateSimulationPhaseSpinBox = QtWidgets.QSpinBox(ResearchWidget)
        self.fateSimulationPhaseSpinBox.setEnabled(False)
        self.fateSimulationPhaseSpinBox.setMaximum(5)
        self.fateSimulationPhaseSpinBox.setObjectName("fateSimulationPhaseSpinBox")
        self.gridLayout.addWidget(self.fateSimulationPhaseSpinBox, 3, 4, 1, 1)
        self.shipNameLabel = QtWidgets.QLabel(ResearchWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.shipNameLabel.setFont(font)
        self.shipNameLabel.setObjectName("shipNameLabel")
        self.gridLayout.addWidget(self.shipNameLabel, 0, 0, 1, 5)

        self.retranslateUi(ResearchWidget)
        QtCore.QMetaObject.connectSlotsByName(ResearchWidget)
        ResearchWidget.setTabOrder(self.researchLevelSpinBox, self.currentBpSpinBox)
        ResearchWidget.setTabOrder(self.currentBpSpinBox, self.fateSimulationPhaseSpinBox)
        ResearchWidget.setTabOrder(self.fateSimulationPhaseSpinBox, self.strengthenLevelTableWidget)

    def retranslateUi(self, ResearchWidget):
        ResearchWidget.setWindowTitle(QtWidgets.QApplication.translate("ResearchWidget", "Form", None, -1))
        self.shipIconLabel.setText(QtWidgets.QApplication.translate("ResearchWidget", "ShipIcon", None, -1))
        self.fateSimulationPhaseLabel.setText(QtWidgets.QApplication.translate("ResearchWidget", "Fate Simulation phase", None, -1))
        self.currentBpLabel.setText(QtWidgets.QApplication.translate("ResearchWidget", "Current blueprints owned", None, -1))
        self.strengthenLevelTableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("ResearchWidget", "Required blueprints", None, -1))
        self.strengthenLevelTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("ResearchWidget", "Level 5", None, -1))
        self.strengthenLevelTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("ResearchWidget", "Level 10", None, -1))
        self.strengthenLevelTableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("ResearchWidget", "Level 15", None, -1))
        self.strengthenLevelTableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("ResearchWidget", "Level 20", None, -1))
        self.strengthenLevelTableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("ResearchWidget", "Level 25", None, -1))
        self.strengthenLevelTableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("ResearchWidget", "Level 30", None, -1))
        self.researchLevelLabel.setText(QtWidgets.QApplication.translate("ResearchWidget", "Research level", None, -1))
        self.bpNeededPerLevelTitleLabel.setText(QtWidgets.QApplication.translate("ResearchWidget", "Blueprints needed per Strengthen level", None, -1))
        self.shipNameLabel.setText(QtWidgets.QApplication.translate("ResearchWidget", "ShipName", None, -1))

