# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shipfu_filter.ui',
# licensing of 'shipfu_filter.ui' applies.
#
# Created: Wed Jan 15 16:23:30 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ShipfuFilter(object):
    def setupUi(self, ShipfuFilter):
        ShipfuFilter.setObjectName("ShipfuFilter")
        ShipfuFilter.resize(585, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShipfuFilter.sizePolicy().hasHeightForWidth())
        ShipfuFilter.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(ShipfuFilter)
        self.gridLayout.setObjectName("gridLayout")
        self.filterTitle2Label = QtWidgets.QLabel(ShipfuFilter)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.filterTitle2Label.setFont(font)
        self.filterTitle2Label.setObjectName("filterTitle2Label")
        self.gridLayout.addWidget(self.filterTitle2Label, 2, 0, 1, 9)
        self.researchHLayout = QtWidgets.QHBoxLayout()
        self.researchHLayout.setObjectName("researchHLayout")
        self.researchLabel = QtWidgets.QLabel(ShipfuFilter)
        self.researchLabel.setObjectName("researchLabel")
        self.researchHLayout.addWidget(self.researchLabel)
        self.researchCheckBox = QtWidgets.QCheckBox(ShipfuFilter)
        self.researchCheckBox.setText("")
        self.researchCheckBox.setChecked(True)
        self.researchCheckBox.setObjectName("researchCheckBox")
        self.researchHLayout.addWidget(self.researchCheckBox)
        self.gridLayout.addLayout(self.researchHLayout, 4, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nameLabel = QtWidgets.QLabel(ShipfuFilter)
        self.nameLabel.setObjectName("nameLabel")
        self.horizontalLayout_3.addWidget(self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(ShipfuFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameLineEdit.sizePolicy().hasHeightForWidth())
        self.nameLineEdit.setSizePolicy(sizePolicy)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(128, 0))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.horizontalLayout_3.addWidget(self.nameLineEdit)
        self.rarityLabel = QtWidgets.QLabel(ShipfuFilter)
        self.rarityLabel.setObjectName("rarityLabel")
        self.horizontalLayout_3.addWidget(self.rarityLabel)
        self.rarityComboBox = QtWidgets.QComboBox(ShipfuFilter)
        self.rarityComboBox.setCurrentText("")
        self.rarityComboBox.setObjectName("rarityComboBox")
        self.horizontalLayout_3.addWidget(self.rarityComboBox)
        self.nationLabel = QtWidgets.QLabel(ShipfuFilter)
        self.nationLabel.setObjectName("nationLabel")
        self.horizontalLayout_3.addWidget(self.nationLabel)
        self.nationComboBox = QtWidgets.QComboBox(ShipfuFilter)
        self.nationComboBox.setObjectName("nationComboBox")
        self.horizontalLayout_3.addWidget(self.nationComboBox)
        self.shipTypeLabel = QtWidgets.QLabel(ShipfuFilter)
        self.shipTypeLabel.setObjectName("shipTypeLabel")
        self.horizontalLayout_3.addWidget(self.shipTypeLabel)
        self.shipTypeComboBox = QtWidgets.QComboBox(ShipfuFilter)
        self.shipTypeComboBox.setObjectName("shipTypeComboBox")
        self.horizontalLayout_3.addWidget(self.shipTypeComboBox)
        self.positionLabel = QtWidgets.QLabel(ShipfuFilter)
        self.positionLabel.setObjectName("positionLabel")
        self.horizontalLayout_3.addWidget(self.positionLabel)
        self.positionComboBox = QtWidgets.QComboBox(ShipfuFilter)
        self.positionComboBox.setObjectName("positionComboBox")
        self.positionComboBox.addItem("")
        self.positionComboBox.addItem("")
        self.positionComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.positionComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 9)
        self.eventHLayout = QtWidgets.QHBoxLayout()
        self.eventHLayout.setObjectName("eventHLayout")
        self.eventLabel = QtWidgets.QLabel(ShipfuFilter)
        self.eventLabel.setObjectName("eventLabel")
        self.eventHLayout.addWidget(self.eventLabel)
        self.eventCheckBox = QtWidgets.QCheckBox(ShipfuFilter)
        self.eventCheckBox.setText("")
        self.eventCheckBox.setChecked(True)
        self.eventCheckBox.setObjectName("eventCheckBox")
        self.eventHLayout.addWidget(self.eventCheckBox)
        self.gridLayout.addLayout(self.eventHLayout, 4, 3, 1, 1)
        self.dropHLayout = QtWidgets.QHBoxLayout()
        self.dropHLayout.setObjectName("dropHLayout")
        self.dropLabel = QtWidgets.QLabel(ShipfuFilter)
        self.dropLabel.setObjectName("dropLabel")
        self.dropHLayout.addWidget(self.dropLabel)
        self.dropCheckBox = QtWidgets.QCheckBox(ShipfuFilter)
        self.dropCheckBox.setText("")
        self.dropCheckBox.setChecked(True)
        self.dropCheckBox.setObjectName("dropCheckBox")
        self.dropHLayout.addWidget(self.dropCheckBox)
        self.gridLayout.addLayout(self.dropHLayout, 4, 1, 1, 1)
        self.collectionHLayout = QtWidgets.QHBoxLayout()
        self.collectionHLayout.setObjectName("collectionHLayout")
        self.collectionLabel = QtWidgets.QLabel(ShipfuFilter)
        self.collectionLabel.setObjectName("collectionLabel")
        self.collectionHLayout.addWidget(self.collectionLabel)
        self.collectionCheckBox = QtWidgets.QCheckBox(ShipfuFilter)
        self.collectionCheckBox.setText("")
        self.collectionCheckBox.setChecked(True)
        self.collectionCheckBox.setObjectName("collectionCheckBox")
        self.collectionHLayout.addWidget(self.collectionCheckBox)
        self.gridLayout.addLayout(self.collectionHLayout, 4, 5, 1, 1)
        self.loginRewardHLayout = QtWidgets.QHBoxLayout()
        self.loginRewardHLayout.setObjectName("loginRewardHLayout")
        self.loginRewardLabel = QtWidgets.QLabel(ShipfuFilter)
        self.loginRewardLabel.setObjectName("loginRewardLabel")
        self.loginRewardHLayout.addWidget(self.loginRewardLabel)
        self.loginRewardCheckBox = QtWidgets.QCheckBox(ShipfuFilter)
        self.loginRewardCheckBox.setText("")
        self.loginRewardCheckBox.setChecked(True)
        self.loginRewardCheckBox.setObjectName("loginRewardCheckBox")
        self.loginRewardHLayout.addWidget(self.loginRewardCheckBox)
        self.gridLayout.addLayout(self.loginRewardHLayout, 4, 6, 1, 1)
        self.buildHLayout = QtWidgets.QHBoxLayout()
        self.buildHLayout.setObjectName("buildHLayout")
        self.buildLabel = QtWidgets.QLabel(ShipfuFilter)
        self.buildLabel.setObjectName("buildLabel")
        self.buildHLayout.addWidget(self.buildLabel)
        self.buildCheckBox = QtWidgets.QCheckBox(ShipfuFilter)
        self.buildCheckBox.setText("")
        self.buildCheckBox.setChecked(True)
        self.buildCheckBox.setObjectName("buildCheckBox")
        self.buildHLayout.addWidget(self.buildCheckBox)
        self.gridLayout.addLayout(self.buildHLayout, 4, 0, 1, 1)
        self.filterTitle1Label = QtWidgets.QLabel(ShipfuFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterTitle1Label.sizePolicy().hasHeightForWidth())
        self.filterTitle1Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.filterTitle1Label.setFont(font)
        self.filterTitle1Label.setObjectName("filterTitle1Label")
        self.gridLayout.addWidget(self.filterTitle1Label, 0, 0, 1, 9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 9, 1, 1)
        self.shopHLayout = QtWidgets.QHBoxLayout()
        self.shopHLayout.setObjectName("shopHLayout")
        self.shopLabel = QtWidgets.QLabel(ShipfuFilter)
        self.shopLabel.setObjectName("shopLabel")
        self.shopHLayout.addWidget(self.shopLabel)
        self.shopCheckBox = QtWidgets.QCheckBox(ShipfuFilter)
        self.shopCheckBox.setText("")
        self.shopCheckBox.setChecked(True)
        self.shopCheckBox.setObjectName("shopCheckBox")
        self.shopHLayout.addWidget(self.shopCheckBox)
        self.gridLayout.addLayout(self.shopHLayout, 4, 2, 1, 1)
        self.resetFiltersPushButton = QtWidgets.QPushButton(ShipfuFilter)
        self.resetFiltersPushButton.setObjectName("resetFiltersPushButton")
        self.gridLayout.addWidget(self.resetFiltersPushButton, 5, 0, 1, 1)

        self.retranslateUi(ShipfuFilter)
        QtCore.QMetaObject.connectSlotsByName(ShipfuFilter)
        ShipfuFilter.setTabOrder(self.nameLineEdit, self.rarityComboBox)
        ShipfuFilter.setTabOrder(self.rarityComboBox, self.nationComboBox)
        ShipfuFilter.setTabOrder(self.nationComboBox, self.shipTypeComboBox)
        ShipfuFilter.setTabOrder(self.shipTypeComboBox, self.positionComboBox)
        ShipfuFilter.setTabOrder(self.positionComboBox, self.buildCheckBox)
        ShipfuFilter.setTabOrder(self.buildCheckBox, self.dropCheckBox)
        ShipfuFilter.setTabOrder(self.dropCheckBox, self.shopCheckBox)
        ShipfuFilter.setTabOrder(self.shopCheckBox, self.eventCheckBox)
        ShipfuFilter.setTabOrder(self.eventCheckBox, self.researchCheckBox)
        ShipfuFilter.setTabOrder(self.researchCheckBox, self.collectionCheckBox)
        ShipfuFilter.setTabOrder(self.collectionCheckBox, self.loginRewardCheckBox)
        ShipfuFilter.setTabOrder(self.loginRewardCheckBox, self.resetFiltersPushButton)

    def retranslateUi(self, ShipfuFilter):
        ShipfuFilter.setWindowTitle(QtWidgets.QApplication.translate("ShipfuFilter", "Form", None, -1))
        self.filterTitle2Label.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Obtention filters", None, -1))
        self.researchLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Researches", None, -1))
        self.nameLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Name", None, -1))
        self.nameLineEdit.setPlaceholderText(QtWidgets.QApplication.translate("ShipfuFilter", "Ship name", None, -1))
        self.rarityLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Rarity", None, -1))
        self.nationLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Nation", None, -1))
        self.shipTypeLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Ship type", None, -1))
        self.positionLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Position", None, -1))
        self.positionComboBox.setItemText(0, QtWidgets.QApplication.translate("ShipfuFilter", "Main Fleet/Vanguard", None, -1))
        self.positionComboBox.setItemText(1, QtWidgets.QApplication.translate("ShipfuFilter", "Main Fleet", None, -1))
        self.positionComboBox.setItemText(2, QtWidgets.QApplication.translate("ShipfuFilter", "Vanguard", None, -1))
        self.eventLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Events", None, -1))
        self.dropLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Drops", None, -1))
        self.collectionLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Collection", None, -1))
        self.loginRewardLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Login Reward", None, -1))
        self.buildLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Builds", None, -1))
        self.filterTitle1Label.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Basic filters", None, -1))
        self.shopLabel.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Shops", None, -1))
        self.resetFiltersPushButton.setText(QtWidgets.QApplication.translate("ShipfuFilter", "Reset filters", None, -1))

