# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shop_item_widget.ui',
# licensing of 'shop_item_widget.ui' applies.
#
# Created: Wed Jan 15 16:23:30 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ShopItemWidget(object):
    def setupUi(self, ShopItemWidget):
        ShopItemWidget.setObjectName("ShopItemWidget")
        ShopItemWidget.resize(400, 300)
        ShopItemWidget.setFrameShape(QtWidgets.QFrame.Box)
        ShopItemWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.gridLayout = QtWidgets.QGridLayout(ShopItemWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.itemIconLabel = QtWidgets.QLabel(ShopItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemIconLabel.sizePolicy().hasHeightForWidth())
        self.itemIconLabel.setSizePolicy(sizePolicy)
        self.itemIconLabel.setMinimumSize(QtCore.QSize(50, 50))
        self.itemIconLabel.setMaximumSize(QtCore.QSize(50, 50))
        self.itemIconLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.itemIconLabel.setObjectName("itemIconLabel")
        self.gridLayout.addWidget(self.itemIconLabel, 0, 0, 1, 1)
        self.itemNameLabel = QtWidgets.QLabel(ShopItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemNameLabel.sizePolicy().hasHeightForWidth())
        self.itemNameLabel.setSizePolicy(sizePolicy)
        self.itemNameLabel.setWordWrap(True)
        self.itemNameLabel.setObjectName("itemNameLabel")
        self.gridLayout.addWidget(self.itemNameLabel, 0, 1, 1, 1)
        self.priceUnitTitleLabel = QtWidgets.QLabel(ShopItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceUnitTitleLabel.sizePolicy().hasHeightForWidth())
        self.priceUnitTitleLabel.setSizePolicy(sizePolicy)
        self.priceUnitTitleLabel.setObjectName("priceUnitTitleLabel")
        self.gridLayout.addWidget(self.priceUnitTitleLabel, 1, 0, 1, 2)
        self.priceUnitLabel = QtWidgets.QLabel(ShopItemWidget)
        self.priceUnitLabel.setObjectName("priceUnitLabel")
        self.gridLayout.addWidget(self.priceUnitLabel, 1, 2, 1, 1)
        self.usualMaxTitleLabel = QtWidgets.QLabel(ShopItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usualMaxTitleLabel.sizePolicy().hasHeightForWidth())
        self.usualMaxTitleLabel.setSizePolicy(sizePolicy)
        self.usualMaxTitleLabel.setObjectName("usualMaxTitleLabel")
        self.gridLayout.addWidget(self.usualMaxTitleLabel, 2, 0, 1, 2)
        self.quantityLabel = QtWidgets.QLabel(ShopItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantityLabel.sizePolicy().hasHeightForWidth())
        self.quantityLabel.setSizePolicy(sizePolicy)
        self.quantityLabel.setObjectName("quantityLabel")
        self.gridLayout.addWidget(self.quantityLabel, 3, 0, 1, 2)
        self.quantitySpinBox = QtWidgets.QSpinBox(ShopItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantitySpinBox.sizePolicy().hasHeightForWidth())
        self.quantitySpinBox.setSizePolicy(sizePolicy)
        self.quantitySpinBox.setMaximum(9999)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.gridLayout.addWidget(self.quantitySpinBox, 3, 2, 1, 1)
        self.totalTitleLabel = QtWidgets.QLabel(ShopItemWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalTitleLabel.sizePolicy().hasHeightForWidth())
        self.totalTitleLabel.setSizePolicy(sizePolicy)
        self.totalTitleLabel.setObjectName("totalTitleLabel")
        self.gridLayout.addWidget(self.totalTitleLabel, 4, 0, 1, 2)
        self.usualMaxLabel = QtWidgets.QLabel(ShopItemWidget)
        self.usualMaxLabel.setObjectName("usualMaxLabel")
        self.gridLayout.addWidget(self.usualMaxLabel, 2, 2, 1, 1)
        self.totalLabel = QtWidgets.QLabel(ShopItemWidget)
        self.totalLabel.setObjectName("totalLabel")
        self.gridLayout.addWidget(self.totalLabel, 4, 2, 1, 1)

        self.retranslateUi(ShopItemWidget)
        QtCore.QMetaObject.connectSlotsByName(ShopItemWidget)

    def retranslateUi(self, ShopItemWidget):
        ShopItemWidget.setWindowTitle(QtWidgets.QApplication.translate("ShopItemWidget", "Form", None, -1))
        self.itemIconLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "ItemIcon", None, -1))
        self.itemNameLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "ItemName", None, -1))
        self.priceUnitTitleLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "Price/unit:", None, -1))
        self.priceUnitLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "{price_unit}", None, -1))
        self.usualMaxTitleLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "Usual maximum unit per event:", None, -1))
        self.quantityLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "Quantity wanted:", None, -1))
        self.totalTitleLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "Total event tokens required:", None, -1))
        self.usualMaxLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "{usual_max}", None, -1))
        self.totalLabel.setText(QtWidgets.QApplication.translate("ShopItemWidget", "{total}", None, -1))

