# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tool_damage_calc.ui',
# licensing of 'tool_damage_calc.ui' applies.
#
# Created: Wed Jan 15 16:23:31 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ToolDamageCalc(object):
    def setupUi(self, ToolDamageCalc):
        ToolDamageCalc.setObjectName("ToolDamageCalc")
        ToolDamageCalc.resize(718, 568)
        self.gridLayout = QtWidgets.QGridLayout(ToolDamageCalc)
        self.gridLayout.setObjectName("gridLayout")
        self.explanationLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.explanationLabel.setWordWrap(True)
        self.explanationLabel.setMargin(0)
        self.explanationLabel.setOpenExternalLinks(True)
        self.explanationLabel.setObjectName("explanationLabel")
        self.gridLayout.addWidget(self.explanationLabel, 0, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 9, 1)
        self.damageStatSpinBox = QtWidgets.QSpinBox(ToolDamageCalc)
        self.damageStatSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.damageStatSpinBox.setMaximum(999)
        self.damageStatSpinBox.setObjectName("damageStatSpinBox")
        self.gridLayout_2.addWidget(self.damageStatSpinBox, 0, 1, 1, 1)
        self.equipmentDmgTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.equipmentDmgTitleLabel.setObjectName("equipmentDmgTitleLabel")
        self.gridLayout_2.addWidget(self.equipmentDmgTitleLabel, 1, 0, 1, 1)
        self.shellsPerVolleyTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.shellsPerVolleyTitleLabel.setObjectName("shellsPerVolleyTitleLabel")
        self.gridLayout_2.addWidget(self.shellsPerVolleyTitleLabel, 3, 0, 1, 1)
        self.shellsPerVolleySpinBox = QtWidgets.QSpinBox(ToolDamageCalc)
        self.shellsPerVolleySpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.shellsPerVolleySpinBox.setMinimum(1)
        self.shellsPerVolleySpinBox.setObjectName("shellsPerVolleySpinBox")
        self.gridLayout_2.addWidget(self.shellsPerVolleySpinBox, 3, 1, 1, 1)
        self.mediumArmorMultSpinBox = QtWidgets.QSpinBox(ToolDamageCalc)
        self.mediumArmorMultSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.mediumArmorMultSpinBox.setMaximum(999)
        self.mediumArmorMultSpinBox.setObjectName("mediumArmorMultSpinBox")
        self.gridLayout_2.addWidget(self.mediumArmorMultSpinBox, 7, 1, 1, 1)
        self.fireRateDoubleSpinBox = QtWidgets.QDoubleSpinBox(ToolDamageCalc)
        self.fireRateDoubleSpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.fireRateDoubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fireRateDoubleSpinBox.setProperty("value", 1.0)
        self.fireRateDoubleSpinBox.setObjectName("fireRateDoubleSpinBox")
        self.gridLayout_2.addWidget(self.fireRateDoubleSpinBox, 2, 1, 1, 1)
        self.slotEffTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.slotEffTitleLabel.setObjectName("slotEffTitleLabel")
        self.gridLayout_2.addWidget(self.slotEffTitleLabel, 5, 0, 1, 1)
        self.heavyArmorMultTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.heavyArmorMultTitleLabel.setObjectName("heavyArmorMultTitleLabel")
        self.gridLayout_2.addWidget(self.heavyArmorMultTitleLabel, 8, 0, 1, 1)
        self.heavyArmorMultSpinBox = QtWidgets.QSpinBox(ToolDamageCalc)
        self.heavyArmorMultSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.heavyArmorMultSpinBox.setMaximum(999)
        self.heavyArmorMultSpinBox.setObjectName("heavyArmorMultSpinBox")
        self.gridLayout_2.addWidget(self.heavyArmorMultSpinBox, 8, 1, 1, 1)
        self.lightArmorMultTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.lightArmorMultTitleLabel.setObjectName("lightArmorMultTitleLabel")
        self.gridLayout_2.addWidget(self.lightArmorMultTitleLabel, 6, 0, 1, 1)
        self.lightArmorMultSpinBox = QtWidgets.QSpinBox(ToolDamageCalc)
        self.lightArmorMultSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.lightArmorMultSpinBox.setMaximum(999)
        self.lightArmorMultSpinBox.setObjectName("lightArmorMultSpinBox")
        self.gridLayout_2.addWidget(self.lightArmorMultSpinBox, 6, 1, 1, 1)
        self.fireRateTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.fireRateTitleLabel.setObjectName("fireRateTitleLabel")
        self.gridLayout_2.addWidget(self.fireRateTitleLabel, 2, 0, 1, 1)
        self.mediumArmorMultTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.mediumArmorMultTitleLabel.setObjectName("mediumArmorMultTitleLabel")
        self.gridLayout_2.addWidget(self.mediumArmorMultTitleLabel, 7, 0, 1, 1)
        self.equipmentDmgSpinBox = QtWidgets.QSpinBox(ToolDamageCalc)
        self.equipmentDmgSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.equipmentDmgSpinBox.setMaximum(999)
        self.equipmentDmgSpinBox.setObjectName("equipmentDmgSpinBox")
        self.gridLayout_2.addWidget(self.equipmentDmgSpinBox, 1, 1, 1, 1)
        self.weaponCoeffTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.weaponCoeffTitleLabel.setObjectName("weaponCoeffTitleLabel")
        self.gridLayout_2.addWidget(self.weaponCoeffTitleLabel, 4, 0, 1, 1)
        self.damageStatTitleLabel = QtWidgets.QLabel(ToolDamageCalc)
        self.damageStatTitleLabel.setObjectName("damageStatTitleLabel")
        self.gridLayout_2.addWidget(self.damageStatTitleLabel, 0, 0, 1, 1)
        self.slotEffSpinBox = QtWidgets.QSpinBox(ToolDamageCalc)
        self.slotEffSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.slotEffSpinBox.setMaximum(999)
        self.slotEffSpinBox.setObjectName("slotEffSpinBox")
        self.gridLayout_2.addWidget(self.slotEffSpinBox, 5, 1, 1, 1)
        self.weaponCoeffSpinBox = QtWidgets.QSpinBox(ToolDamageCalc)
        self.weaponCoeffSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.weaponCoeffSpinBox.setMaximum(999)
        self.weaponCoeffSpinBox.setObjectName("weaponCoeffSpinBox")
        self.gridLayout_2.addWidget(self.weaponCoeffSpinBox, 4, 1, 1, 1)
        self.line = QtWidgets.QFrame(ToolDamageCalc)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 9, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 3)
        self.damageTableWidget = QtWidgets.QTableWidget(ToolDamageCalc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.damageTableWidget.sizePolicy().hasHeightForWidth())
        self.damageTableWidget.setSizePolicy(sizePolicy)
        self.damageTableWidget.setMinimumSize(QtCore.QSize(415, 115))
        self.damageTableWidget.setMaximumSize(QtCore.QSize(16777215, 115))
        self.damageTableWidget.setObjectName("damageTableWidget")
        self.damageTableWidget.setColumnCount(3)
        self.damageTableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.damageTableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.damageTableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.damageTableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.damageTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.damageTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.damageTableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.damageTableWidget, 4, 0, 1, 3)
        self.resultsLabel = QtWidgets.QLabel(ToolDamageCalc)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.resultsLabel.setFont(font)
        self.resultsLabel.setObjectName("resultsLabel")
        self.gridLayout.addWidget(self.resultsLabel, 3, 0, 1, 1)

        self.retranslateUi(ToolDamageCalc)
        QtCore.QMetaObject.connectSlotsByName(ToolDamageCalc)
        ToolDamageCalc.setTabOrder(self.damageStatSpinBox, self.equipmentDmgSpinBox)
        ToolDamageCalc.setTabOrder(self.equipmentDmgSpinBox, self.fireRateDoubleSpinBox)
        ToolDamageCalc.setTabOrder(self.fireRateDoubleSpinBox, self.shellsPerVolleySpinBox)
        ToolDamageCalc.setTabOrder(self.shellsPerVolleySpinBox, self.weaponCoeffSpinBox)
        ToolDamageCalc.setTabOrder(self.weaponCoeffSpinBox, self.slotEffSpinBox)
        ToolDamageCalc.setTabOrder(self.slotEffSpinBox, self.lightArmorMultSpinBox)
        ToolDamageCalc.setTabOrder(self.lightArmorMultSpinBox, self.mediumArmorMultSpinBox)
        ToolDamageCalc.setTabOrder(self.mediumArmorMultSpinBox, self.heavyArmorMultSpinBox)
        ToolDamageCalc.setTabOrder(self.heavyArmorMultSpinBox, self.damageTableWidget)

    def retranslateUi(self, ToolDamageCalc):
        ToolDamageCalc.setWindowTitle(QtWidgets.QApplication.translate("ToolDamageCalc", "Form", None, -1))
        self.explanationLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "<html><head/><body><p>Using this tool, you can compute an estimation of your ship\'s damage. To do so, you will need a lot of informations. I recommend you to use the Azur Lane Wiki. First, click on the page corresponding to your ship\'s gun in this <a href=\"https://azurlane.koumakan.jp/Category:Equipment\"><span style=\" text-decoration: underline; color:#007af4;\">page</span></a>. Then, go to this <a href=\"https://azurlane.koumakan.jp/Guide:_Equipment#Armor_Multipliers\"><span style=\" text-decoration: underline; color:#007af4;\">page</span></a> to get the &quot;Armor multiplier&quot; stat corresponding to your gun type and ammo type.</p><p>&quot;Damage per volley&quot; and &quot;Theoretical DPS&quot; assume that every shell hits one enemy.</p><p>Note: currently, the calculator assumes no bonus firepower/torpedo from fleet formation, skills, nor bonus/malus from level difference.</p></body></html>", None, -1))
        self.equipmentDmgTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Equipment damage:", None, -1))
        self.shellsPerVolleyTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Shells fired per volley:", None, -1))
        self.slotEffTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Slot efficiency (%):", None, -1))
        self.heavyArmorMultTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Heavy Armor multiplier (%):", None, -1))
        self.lightArmorMultTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Light Armor multiplier (%):", None, -1))
        self.fireRateTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Fire rate:", None, -1))
        self.mediumArmorMultTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Medium Armor multiplier (%):", None, -1))
        self.weaponCoeffTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Weapon coefficient (%):", None, -1))
        self.damageStatTitleLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Firepower/Torpedo:", None, -1))
        self.damageTableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Damage per shell", None, -1))
        self.damageTableWidget.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Damage per volley", None, -1))
        self.damageTableWidget.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Theoretical DPS", None, -1))
        self.damageTableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Light", None, -1))
        self.damageTableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Medium", None, -1))
        self.damageTableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Heavy", None, -1))
        self.resultsLabel.setText(QtWidgets.QApplication.translate("ToolDamageCalc", "Results:", None, -1))

